/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import database_mahasiswa.DeleteAnggota;
import database_mahasiswa.DatabaseConnector;
import java.util.ArrayList;
import java.util.List;
import java.awt.Component;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Limun
 */
public class DeleteAgt extends javax.swing.JFrame {

    /**
     * Creates new form DeleteAgt
     */
    private static final String DEFAULT_Nama_TEXT = "Nama Yang Ingin Dihapus";
    private static final String DEFAULT_NIM_TEXT = "NIM Yang Ingin Dihapus";
    private static final String DEFAULT_FAKULTAS_TEXT = "Fakultas Yang Ingin Dihapus";
    private static final String DEFAULT_PRODI_TEXT = "Prodi Yang Ingin Dihapus";
    public DeleteAgt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogWarning = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextNIM = new javax.swing.JTextField();
        LabelNIM = new javax.swing.JLabel();
        LabelFakultas = new javax.swing.JLabel();
        TextFakultas = new javax.swing.JTextField();
        TextProdi = new javax.swing.JTextField();
        LabelProdi = new javax.swing.JLabel();
        ListNama = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        LabelNama = new javax.swing.JLabel();

        label1.setFont(new java.awt.Font("Clarendon BT", 0, 18)); // NOI18N
        label1.setText("Data Berhasil Dimasukkan");

        javax.swing.GroupLayout DialogWarningLayout = new javax.swing.GroupLayout(DialogWarning.getContentPane());
        DialogWarning.getContentPane().setLayout(DialogWarningLayout);
        DialogWarningLayout.setHorizontalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        DialogWarningLayout.setVerticalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Hapus Data Anggota");

        TextNIM.setText("NIM Yang Ingin Dihapus");
        TextNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNIMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNIMFocusLost(evt);
            }
        });
        TextNIM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextNIMMouseClicked(evt);
            }
        });
        TextNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNIMActionPerformed(evt);
            }
        });

        LabelNIM.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelNIM.setText("NIM");

        LabelFakultas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelFakultas.setText("Fakultas");

        TextFakultas.setText("Fakultas Yang Ingin Dihapus");
        TextFakultas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFakultasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFakultasFocusLost(evt);
            }
        });
        TextFakultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFakultasMouseClicked(evt);
            }
        });
        TextFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFakultasActionPerformed(evt);
            }
        });

        TextProdi.setText("Prodi Yang Ingin Dihapus");
        TextProdi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextProdiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextProdiFocusLost(evt);
            }
        });
        TextProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextProdiMouseClicked(evt);
            }
        });

        LabelProdi.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelProdi.setText("Prodi");

        ListNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Yang Ingin Dihapus" }));
        ListNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListNamaMouseClicked(evt);
            }
        });
        ListNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListNamaActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        SubmitButton.setText("Delete");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Bebas Neue", 0, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        LabelNama.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelNama.setText("Nama ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelNama)
                                    .addComponent(LabelFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNIM)
                                    .addComponent(TextProdi)
                                    .addComponent(TextFakultas)
                                    .addComponent(ListNama, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BackButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(ListNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProdi))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNIMActionPerformed

    private void TextFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFakultasActionPerformed

    private void TextNIMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNIMMouseClicked
        // TODO add your handling code here:
        if (TextNIM.getText().equals(DEFAULT_NIM_TEXT)) {
            TextNIM.setText("");
        }
    }//GEN-LAST:event_TextNIMMouseClicked

    private void TextFakultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFakultasMouseClicked
        // TODO add your handling code here:
        if (TextFakultas.getText().equals(DEFAULT_FAKULTAS_TEXT)) {
            TextFakultas.setText("");
        }
    }//GEN-LAST:event_TextFakultasMouseClicked

    private void TextFakultasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFakultasFocusGained
        // TODO add your handling code here:
        if (TextFakultas.getText().isEmpty()) {
            TextFakultas.setText(DEFAULT_FAKULTAS_TEXT);
        }
    }//GEN-LAST:event_TextFakultasFocusGained

    private void TextProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextProdiMouseClicked
        // TODO add your handling code here:
        if (TextProdi.getText().equals(DEFAULT_PRODI_TEXT)) {
            TextProdi.setText("");
        }
    }//GEN-LAST:event_TextProdiMouseClicked

    private void TextProdiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProdiFocusGained
        // TODO add your handling code here:
        if (TextProdi.getText().isEmpty()) {
            TextProdi.setText(DEFAULT_PRODI_TEXT);
        }
    }//GEN-LAST:event_TextProdiFocusGained

    private void TextNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNIMFocusLost
        // TODO add your handling code here:
        if ( TextNIM.getText().isEmpty()){
            TextNIM.setText(DEFAULT_NIM_TEXT);
        }
    }//GEN-LAST:event_TextNIMFocusLost

    private void TextNIMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNIMFocusGained
        // TODO add your handling code here:
        if (TextNIM.getText().isEmpty()) {
            TextNIM.setText(DEFAULT_NIM_TEXT);
        }
    }//GEN-LAST:event_TextNIMFocusGained

    private void TextFakultasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFakultasFocusLost
        // TODO add your handling code here:
        if ( TextFakultas.getText().isEmpty()){
            TextFakultas.setText(DEFAULT_FAKULTAS_TEXT);
        }
    }//GEN-LAST:event_TextFakultasFocusLost

    private void TextProdiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProdiFocusLost
        // TODO add your handling code here:
        if ( TextProdi.getText().isEmpty()){
            TextProdi.setText(DEFAULT_PRODI_TEXT);
        }
    }//GEN-LAST:event_TextProdiFocusLost

    private void ListNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListNamaActionPerformed
    String selectedName = (String) ListNama.getSelectedItem();

       // Fetch data from the database based on the selected name
       try {
           // Replace the following lines with your database retrieval logic
           List<String> nimList = DatabaseConnector.getNIMFromDatabase(selectedName);
           List<String> fakultasList = DatabaseConnector.getFakultasFromDatabase(selectedName);
           List<String> prodiList = DatabaseConnector.getProdiFromDatabase(selectedName);

           // Check if the lists are not empty before setting the text
           if (!nimList.isEmpty()) {
               TextNIM.setText(nimList.get(0)); // Assuming there's only one NIM for a given name
           }

           if (!fakultasList.isEmpty()) {
               TextFakultas.setText(fakultasList.get(0)); // Assuming there's only one Fakultas for a given name
           }

           if (!prodiList.isEmpty()) {
               TextProdi.setText(prodiList.get(0)); // Assuming there's only one Prodi for a given name
           }
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_ListNamaActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
           String nama = (String) ListNama.getSelectedItem();
           String nim = TextNIM.getText();
           String fakultas = TextFakultas.getText();
           String prodi = TextProdi.getText();

           DeleteAnggota.deleteDataAnggota(nama, nim, fakultas, prodi);

           String successDeleteMessage = "Data has been successfully Deleted!";
           JOptionPane.showMessageDialog(this, successDeleteMessage, "Delete", JOptionPane.INFORMATION_MESSAGE);

           Timer timer = new Timer(2000, new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
                   // Close the dialog
                   Window window = SwingUtilities.getWindowAncestor((Component) e.getSource());
                   if (window != null) {
                       window.dispose();
                   }
               }
           });
           timer.setRepeats(false); 
           timer.start();

           DataAnggota framedata = new DataAnggota();
           framedata.setVisible(true);
           dispose();
       } catch (Exception e) {
           // Display error message
           String errorMessage = "Error occurred: " + e.getMessage();
           JOptionPane.showMessageDialog(this, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        DataAnggota datamenu = new DataAnggota();
        datamenu.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ListNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListNamaMouseClicked
        // TODO add your handling code here:
        try {
            List<String> names = DatabaseConnector.getNamesFromDatabase();
            ListNama.removeAllItems();
            for (String name : names) {
                ListNama.addItem(name);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ListNamaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAgt().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JDialog DialogWarning;
    private javax.swing.JLabel LabelFakultas;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelProdi;
    private javax.swing.JComboBox<String> ListNama;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField TextFakultas;
    private javax.swing.JTextField TextNIM;
    private javax.swing.JTextField TextProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
