/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import database_mahasiswa.DeleteAnggota;
import database_mahasiswa.DatabaseConnector;
import java.util.ArrayList;
import java.util.List;
import java.awt.Component;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Limun
 */
public class DeleteAgt extends javax.swing.JFrame {

    /**
     * Creates new form DeleteAgt
     */
    private static final String DEFAULT_Nama_TEXT = "Nama Yang Ingin Dihapus";
    private static final String DEFAULT_NIM_TEXT = "NIM Yang Ingin Dihapus";
    private static final String DEFAULT_FAKULTAS_TEXT = "Fakultas Yang Ingin Dihapus";
    private static final String DEFAULT_PRODI_TEXT = "Prodi Yang Ingin Dihapus";
    public DeleteAgt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogWarning = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        LabelNama = new javax.swing.JLabel();
        TextNIM = new javax.swing.JTextField();
        LabelNIM = new javax.swing.JLabel();
        LabelFakultas = new javax.swing.JLabel();
        TextFakultas = new javax.swing.JTextField();
        TextProdi = new javax.swing.JTextField();
        LabelProdi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ListNama = new javax.swing.JComboBox<>();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        label1.setFont(new java.awt.Font("Clarendon BT", 0, 18)); // NOI18N
        label1.setText("Data Berhasil Dimasukkan");

        javax.swing.GroupLayout DialogWarningLayout = new javax.swing.GroupLayout(DialogWarning.getContentPane());
        DialogWarning.getContentPane().setLayout(DialogWarningLayout);
        DialogWarningLayout.setHorizontalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        DialogWarningLayout.setVerticalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNama.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelNama.setText("Nama ");

        TextNIM.setText("NIM Yang Ingin Dihapus");
        TextNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNIMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNIMFocusLost(evt);
            }
        });
        TextNIM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextNIMMouseClicked(evt);
            }
        });
        TextNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNIMActionPerformed(evt);
            }
        });

        LabelNIM.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelNIM.setText("NIM");

        LabelFakultas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelFakultas.setText("Fakultas");

        TextFakultas.setText("Fakultas Yang Ingin Dihapus");
        TextFakultas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFakultasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextFakultasFocusLost(evt);
            }
        });
        TextFakultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFakultasMouseClicked(evt);
            }
        });
        TextFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFakultasActionPerformed(evt);
            }
        });

        TextProdi.setText("Prodi Yang Ingin Dihapus");
        TextProdi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextProdiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextProdiFocusLost(evt);
            }
        });
        TextProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextProdiMouseClicked(evt);
            }
        });

        LabelProdi.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        LabelProdi.setText("Prodi");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Hapus Data Anggota");

        ListNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Yang Ingin Dihapus" }));
        ListNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListNamaMouseClicked(evt);
            }
        });
        ListNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListNamaActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        SubmitButton.setText("Delete");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Bebas Neue", 0, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNama)
                            .addComponent(LabelFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextNIM)
                            .addComponent(TextProdi)
                            .addComponent(TextFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(ListNama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BackButton)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(ListNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProdi))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNIMActionPerformed

    private void TextFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFakultasActionPerformed

    private void TextNIMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNIMMouseClicked
        // TODO add your handling code here:
        if (TextNIM.getText().equals(DEFAULT_NIM_TEXT)) {
            TextNIM.setText("");
        }
    }//GEN-LAST:event_TextNIMMouseClicked

    private void TextFakultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFakultasMouseClicked
        // TODO add your handling code here:
        if (TextFakultas.getText().equals(DEFAULT_FAKULTAS_TEXT)) {
            TextFakultas.setText("");
        }
    }//GEN-LAST:event_TextFakultasMouseClicked

    private void TextFakultasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFakultasFocusGained
        // TODO add your handling code here:
        if (TextFakultas.getText().isEmpty()) {
            TextFakultas.setText(DEFAULT_FAKULTAS_TEXT);
        }
    }//GEN-LAST:event_TextFakultasFocusGained

    private void TextProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextProdiMouseClicked
        // TODO add your handling code here:
        if (TextProdi.getText().equals(DEFAULT_PRODI_TEXT)) {
            TextProdi.setText("");
        }
    }//GEN-LAST:event_TextProdiMouseClicked

    private void TextProdiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProdiFocusGained
        // TODO add your handling code here:
        if (TextProdi.getText().isEmpty()) {
            TextProdi.setText(DEFAULT_PRODI_TEXT);
        }
    }//GEN-LAST:event_TextProdiFocusGained

    private void TextNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNIMFocusLost
        // TODO add your handling code here:
        if ( TextNIM.getText().isEmpty()){
            TextNIM.setText(DEFAULT_NIM_TEXT);
        }
    }//GEN-LAST:event_TextNIMFocusLost

    private void TextNIMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNIMFocusGained
        // TODO add your handling code here:
        if (TextNIM.getText().isEmpty()) {
            TextNIM.setText(DEFAULT_NIM_TEXT);
        }
    }//GEN-LAST:event_TextNIMFocusGained

    private void TextFakultasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFakultasFocusLost
        // TODO add your handling code here:
        if ( TextFakultas.getText().isEmpty()){
            TextFakultas.setText(DEFAULT_FAKULTAS_TEXT);
        }
    }//GEN-LAST:event_TextFakultasFocusLost

    private void TextProdiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextProdiFocusLost
        // TODO add your handling code here:
        if ( TextProdi.getText().isEmpty()){
            TextProdi.setText(DEFAULT_PRODI_TEXT);
        }
    }//GEN-LAST:event_TextProdiFocusLost

    private void ListNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListNamaActionPerformed
        // TODO add your handling code here:
        try {
            String selectedName = (String) ListNama.getSelectedItem();

            // Fetch data from the database based on the selected name
            // Assuming you have a method in DatabaseConnector to get data by name
            // Update the method signature accordingly
             mahasiswa = DatabaseConnector.getNamesFromDatabase(selectedName);

            // Set the values in the text fields
            TextNIM.setText(mahasiswa.getNIM());
            TextFakultas.setText(mahasiswa.getFakultas());
            TextProdi.setText(mahasiswa.getProdi());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ListNamaActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
           String nama = (String) ListNama.getSelectedItem();
           String nim = TextNIM.getText();
           String fakultas = TextFakultas.getText();
           String prodi = TextProdi.getText();

           DeleteAnggota.deleteDataAnggota(nama, nim, fakultas, prodi);

           String successMessage = "Data has been successfully submitted!";
           JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);

           Timer timer = new Timer(2000, new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
                   // Close the dialog
                   Window window = SwingUtilities.getWindowAncestor((Component) e.getSource());
                   if (window != null) {
                       window.dispose();
                   }
               }
           });
           timer.setRepeats(false); 
           timer.start();

           DataAnggota framedata = new DataAnggota();
           framedata.setVisible(true);
           dispose();
       } catch (Exception e) {
           // Display error message
           String errorMessage = "Error occurred: " + e.getMessage();
           JOptionPane.showMessageDialog(this, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        DataAnggota datamenu = new DataAnggota();
        datamenu.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ListNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListNamaMouseClicked
        // TODO add your handling code here:
        try {
            List<String> names = DatabaseConnector.getNamesFromDatabase();
            ListNama.removeAllItems();
            for (String name : names) {
                ListNama.addItem(name);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ListNamaMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JDialog DialogWarning;
    private javax.swing.JLabel LabelFakultas;
    private javax.swing.JLabel LabelNIM;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelProdi;
    private javax.swing.JComboBox<String> ListNama;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField TextFakultas;
    private javax.swing.JTextField TextNIM;
    private javax.swing.JTextField TextProdi;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
